### ISSUE TITLE
async-dns collision with Akka 2.5.14

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-lib#77]
originally reported by @ignasi35 

Lagom 1.4.7 (via Akka 2.5.14) introduced a bug when deploying with sbt-reactive-app (actually when using reactive-lib's `reactive-lib-service-discovery-lagom14-java`).
The problem is that since Akka 2.5.14 there's two providers for `async-dns`:

1. the implementation in Akka itself ("akka.io.dns.internal.AsyncDnsProvider")
2. the implementation in reactive-lib ("com.lightbend.rp.asyncdns.AsyncDnsProvider")

and Akka 2.5.14 also made its provider the default introducing an ambiguity since users of both libraries now have two reference.conf files with a value for:

```
akka.io.dns.async-dns.provider-object = "..."
```

**Comment by TimMoore** [comment]
AFAICT, this problem _does not_ occur when using `sbt-reactive-app`, because the conflicting definition in `reactive-lib` is not in `reference.conf` but in [`rp-tooling.conf`](https://github.com/lightbend/reactive-lib/blob/master/service-discovery/src/main/resources/rp-tooling.conf). The way `sbt-reactive-app` assembles and loads configuration ensures that this takes precedence over the `reference.conf` in `akka-actor`.

**Comment by TimMoore** [comment]
We're working on a new service locator for Lagom that uses the Akka DNS implementation and avoids this problem: https://github.com/lagom/service-locator-akka-discovery
